version: '3.8'
services:
  web:
    build:
      context: ./backend/asset-management-tool/
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/asset-management-tool/
    ports:
      - 8000:8000
    env_file:
      - ./backend/asset-management-tool/.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data_ams:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=amsuser
      - POSTGRES_PASSWORD=amsuser
      - POSTGRES_DB=ams
  
  frontend:
    restart: always
    command : npm start
    container_name: front
    build:
      context: ./frontend/react-project/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - web
  
  redis:
    image: redis:alpine
  celery:
    restart: always
    build:
      context: ./backend/asset-management-tool/
    command: celery -A config_pannel worker -l info
    volumes:
      - ./:/usr/src/asset-management-tool/
    env_file:
      - ./backend/asset-management-tool/.env.dev
    depends_on:
      - db
      - redis
      - web
volumes:
  postgres_data_ams: