version: '3.8'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/asset-management-tool/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data_ams:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=amsuser
      - POSTGRES_PASSWORD=amsuser
      - POSTGRES_DB=ams
  
  redis:
    image: redis:alpine
  celery:
    restart: always
    build:
      context: .
    command: celery -A config_pannel worker -l info
    volumes:
      - ./:/usr/src/asset-management-tool/
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
      - web
volumes:
  postgres_data_ams: